# Generated by Django 5.2.7 on 2025-11-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=100, verbose_name='Categoría'),
        ),
    ]
