# Generated by Django 5.2.7 on 2025-11-16 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_product_precio_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='caramelo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='precio_total',
        ),
        migrations.AddField(
            model_name='compra',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='api.product'),
            preserve_default=False,
        ),
    ]
